name: Deploy

on:
  push:
    branches:
      -   master  # Specify the target branch for deployment

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      
      - name: FTP Deploy
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ftp.nilesoftdemo.com
          username: nilesoft@raycon.nilesoftdemo.com
          password: 8.O5cM~qp#A+ # Use GitHub secret for password
          protocol: ftp
          local-dir: ./